name: MPManager
version: '${project.version}'
main: mchpixel.mpmanager.MPManager
api-version: '1.20'
load: STARTUP

commands:
  warn:
    description: Warn a certain player
    aliases: [warnplayer]
    permission: mpmanager.operators.warn

  listwarns:
    description: List warnings for a player
    aliases: [listwarnings]
    permission: mpmanager.operators.listwarnings

  removewarns:
    description: Remove warnings for a player
    aliases: [removewarnings]
    permission: mpmanager.operators.removewarnings