name: MPManager
version: '${project.version}'
main: mchpixel.mpmanager.MPManager
api-version: '1.20'
load: STARTUP

commands:
  warn:
    description: "Gives a Player a Warn"
    aliases: [warnplayer, wp]
    permission: mpmanager.operators.warn

  listwarns:
    description: List warnings for a player
    aliases: [listplayerswarnings, listwarnings, lw, lpw]
    permission: mpmanager.operators.listwarnings